---
title: "扎心魔仙提醒您：你复习不完了\U0001F60A（时间函数）"
author: ''
date: '2019-06-15'
slug: 扎心魔仙提醒您-你复习不完了-时间函数
categories: []
tags: []
---
## 慎选闭卷考试的科目！！！😭

这学期，在我自作孽的情况下给自己额外选了两门闭卷考试，所以总共就有三门，致使现在的我复习得崩溃。为了让自己清醒地意识到时间的紧迫性，来看一下各科还有多久就考试了🙄

```{r}
now<- Sys.time()
sadtime<- strptime ("2019-06-23 10:30:00", format = "%Y-%m-%d %H:%M:%S")
difftime(sadtime,now,units = "hours")
print(paste("距离悲伤的毛概考试仅有",sadtime-now,"天，折合",difftime(sadtime,now,units = "hours"),"小时",difftime(sadtime,now,units = "mins"),"分钟",difftime(sadtime,now, units = "secs"),"秒"))
```

##下面是人类行为与社会环境：
```{r}
```


```{r}
now<- Sys.time()
sadtime<- strptime ("2019-06-25 14:30:00", format = "%Y-%m-%d %H:%M:%S")
difftime(sadtime,now,units = "hours")
print(paste("距离选修的人类行为还有",sadtime-now,"天，折合",difftime(sadtime,now,units = "hours"),"小时",difftime(sadtime,now,units = "mins"),"分钟",difftime(sadtime,now, units = "secs"),"秒"))
```
好像还有近六天的样子，先不着急？？？

##下面是比较远的人力资源管理：
```{r}
today <- Sys.Date()
gtd <- as.Date("2019-06-27")   
print(paste("距离人力资源管理考试还有",gtd-today,"天，折合",difftime(gtd,today,units="hours"),"小时",difftime(gtd,today,units = "mins"),"分钟",difftime(gtd,today, units = "secs"),"秒"))
```
所以这门课看上仿佛也还可以？？
但我还有各种作业要交！比如最困难的互联网的两个标准，没有头绪诶😔
